### ISSUE TITLE
Multiple field name with index

### ISSUE THREAD

**Issue by andersonfelix** [ridaamirini/vue-cloneya#15]
What do you think about it:

```html
<input name="example[]['name']" type="text" v-cloneya-input="'Name'">
```

Rendered with index:

```html
<input name="example[0]['name']" type="text" v-cloneya-input="'Name'">
```

My stupid fix:

```javascript
if (_this.multiple) {
   element.domProps['name'] = vnode.data.attrs.name.replace('[]', `[${payload.index}]`)
}
```

**Comment by ridaamirini** [comment]
Ok, sounds good.

It would be nice, if you explain why we should implement this feature.

**Comment by andersonfelix** [comment]
It's useful for projects non-SPA as laravel projects.

**Comment by ridaamirini** [comment]
Feel free to open a PR.

**Comment by andersonfelix** [comment]
Alright!

**Comment by andersonfelix** [comment]
Hi @ridaamirini 

Don't you need to create a new tag?

`"vue-cloneya": "^1.0.10"`

**Comment by ridaamirini** [comment]
I need to publish this `master` to npm. 

I will publish it today or tomorrow.

**Comment by andersonfelix** [comment]
Thanks a lot!
