### ISSUE TITLE
Suggestion - Move up and move down buttons

### ISSUE THREAD

**Issue by andersonfelix** [ridaamirini/vue-cloneya#16]
Hi,

Theses buttons ease on edit mode for example. What do you think about it?

**Comment by ridaamirini** [comment]
Hey @andersonfelix,

i don't think that this fits to this package.

**Comment by andersonfelix** [comment]
Ok. It makes sense.

What do you recommend? A fork?

**Comment by ridaamirini** [comment]
Yes a fork would be a solution
